// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ouauehtpqfvldbvsihpu.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91YXVlaHRwcWZ2bGRidnNpaHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEzMzI0NDQsImV4cCI6MjA0NjkwODQ0NH0.4223Ym_ElH8GL2hO5lYvucPrfOlfYIUHlEXWXs6YO4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);